Repository FRONTENDBOOTCAMP-14th/js-project-team3, pull requests merged in 2025-07, with the labels that each got.

#10 feature - 헤더 컴포넌트 마크업 및 스타일링 완료
  public/images/logo.png
  src/components/header/header.css
  src/components/header/header.html
  src/style.css
Labels: 기능추가

#16 feature - 팀소개 컴포넌트 마크업 및 애니메이션 구현 완료
  index.html
  public/images/member-01-over.png
  public/images/member-01.png
  public/images/member-02-over.png
  public/images/member-02.png
  public/images/member-03-over.png
  public/images/member-03.png
  public/images/member-04-over.png
  public/images/member-04.png
  src/components/team-introduction/team-introduction.css
  src/components/team-introduction/team-introduction.html
  src/components/team-introduction/team-introduction.js
  src/style.css
Labels: 디자인, 기능추가

#18 feature - 바로가기 링크 컴포넌트 마크업 및 스타일링 구현 완료
  index.html
  src/components/main-button/main-button.css
  src/components/main-button/main-button.html
  src/style.css
Labels: 기능추가

#21 feature - 사용자 정보 및 서치바 UI 구현
  index.html
  public/icon/search_icon.svg
  public/images/profile/user-default-img.png
  src/components/otherinfo/other-Info.css
  src/components/otherinfo/other-Info.html
  src/components/otherinfo/other-info.js
  src/components/searchbar/search-Bar.css
  src/components/searchbar/search-Bar.html
  src/components/searchbar/search-Bar.js
  src/components/userinfo/user-Info.css
  src/components/userinfo/user-Info.html
  src/components/userinfo/user-Info.js
  src/style.css
Labels: 디자인, 기능추가

#23 feature - 전적 통계 컴포넌트 마크업 및 스타일링 구현 완료
  index.html
  public/icon/arrow.svg
  public/icon/date.svg
  src/components/total-statistics/total-statistics.css
  src/components/total-statistics/total-statistics.html
  src/components/total-statistics/total-statistics.js
Labels: 디자인

#27 feat: 전적 통계 컴포넌트 API 연동
  src/components/total-statistics/total-statistics.css
  src/components/total-statistics/total-statistics.html
  src/components/total-statistics/total-statistics.js
Labels: 기능추가

#28 feat:전적 페이지 안내 컴포넌트 마크업 및 구현
  index.html
  src/components/score-info/score-info.css
  src/components/score-info/score-info.html
Labels: 기능추가

#33 feat : 코드 컨벤션 추가
  .prettierrc.json
  eslint.config.js
  mock.json
  package-lock.json
  package.json
Labels: 빌드, 기능추가

#34 feat - live컴포넌트 완성
  index.html
  public/images/chzzk-icon.png
  public/images/youtube-icon.png
  src/components/footer/footer.html
  src/components/footer/footer.js
  src/components/header/header.html
  src/components/header/header.js
  src/components/live/live.css
  src/components/live/live.html
  src/components/live/live.js
  src/components/main-visual/main-visual.js
  src/components/news/news.css
  src/components/news/news.js
  src/components/team-introduction/team-introduction.js
  src/components/total-statistics/total-statistics.js
  src/main.js
  vite.config.js
Labels: 리팩토링, 디자인, 기능추가, 접근성, 스타일

#37 accessibility: 메인 버튼 컴포넌트 마크업 수정 완료
  src/components/footer/footer.js
  src/components/header/header.html
  src/components/header/header.js
  src/components/main-button/main-button.html
  src/components/main-visual/main-visual.html
  src/components/main-visual/main-visual.js
  src/components/score-info/score-info.html
  src/components/team-introduction/team-introduction.css
  src/components/team-introduction/team-introduction.html
  src/components/team-introduction/team-introduction.js
  src/components/total-statistics/total-statistics.html
  src/components/total-statistics/total-statistics.js
Labels: 리팩토링, 접근성

#45 feat - 전적 리스트 구현
  src/components/score-detail/score-detail.css
  src/components/score-detail/score-detail.html
  src/components/score-detail/score-detail.js
Labels: 디자인, 초기설정, 기능추가, 접근성

#46 modify: 메인페이지 반응형 및 접근성 개선 완료
  public/images/visual-mobile.png
  src/components/header/header.css
  src/components/main-visual/main-visual.css
  src/components/team-introduction/team-introduction.js
Labels: 디자인, 접근성

#49 design: 푸터 컴포넌트 CSS 수정 완료
  src/components/footer/footer.css
  src/components/footer/footer.html
Labels: 디자인

#53 feat - 유저 정보 UI 병합 및 기능 작성 #52
  src/components/otherinfo/other-Info.css
  src/components/otherinfo/other-info.js
  src/components/userinfo/user-Info.css
  src/components/userinfo/user-Info.js
  src/data/rank_tier_Response.json
  src/data/season_grade_Response.json
  src/data/total_grade_Response.json
  src/style.css
  src/utils/date.js
Labels: 리팩토링, 디자인, 기능추가, 스타일
