Repository FRONTENDBOOTCAMP-14th/js-project-team3, pull requests merged in 2025-08, with the labels that each got.

#58 fix - 치지직 라이브 컴포넌트 api통신 500에러 수정
  netlify.toml
  netlify/functions/api-proxy.js
  src/components/live/live.js
Labels: 버그, 리팩토링

#61 refactor : total-statistics 컴포넌트 템플릿 리터럴 방식 수정 완료
  src/components/total-statistics/total-statistics.js
Labels: 리팩토링

#65 feat : user-info api 연동 #64
  mock.json
  src/components/otherinfo/other-Info.css
  src/components/otherinfo/other-info.js
  src/components/record/record.js
  src/components/score/score.js
  src/components/userinfo/user-Info.css
  src/components/userinfo/user-Info.js
  src/service/user.js
Labels: 디자인, 기능추가

#66 design : total-statistics 컴포넌트 폰트 수정 완료
  src/components/score-info/score-info.js
  src/components/total-statistics/total-statistics.css
  src/components/total-statistics/total-statistics.js
Labels: 디자인

#69 design - Home페이지 간격 수정 및 기타 margin, padding값 등 수정
  src/components/convention/convention.html
  src/components/convention/convention.js
  src/components/home/home.css
  src/components/home/home.html
  src/components/home/home.js
  src/components/live/live.css
  src/components/main-visual/main-visual.html
  src/components/main-visual/main-visual.js
  src/components/news/news.css
  src/components/news/news.js
  src/components/record/record.css
  src/components/record/record.html
  src/components/record/record.js
  src/components/score/score.css
  src/components/score/score.html
  src/components/score/score.js
  src/components/team-introduction/team-introduction.css
  src/components/team-introduction/team-introduction.html
  src/components/team-introduction/team-introduction.js
Labels: 디자인

#77 design : 메인페이지 버튼 컴포넌트 크기 수정 완료
  src/components/main-button/main-button.css
  src/components/main-button/main-button.html
  src/components/main-button/main-button.js
Labels: 디자인

#78 feat - 검색 가이드 이미지 로직 구현
  netlify/functions/api-proxy.js
  public/images/search-guide--no-result-mobile.png
  public/images/search-guide-mobile.png
  public/images/search-guide-no-result-pc.png
  public/images/search-guide-pc.png
  src/components/record/record.html
  src/components/score/score.css
  src/components/score/score.html
  src/components/score/score.js
Labels: 디자인, 기능추가

#81 fix - 치지직 라이브 파라미터값 오류 수정
  netlify/functions/api-proxy.js
Labels: 버그

#83 feat : 사용자 검색 기록 기능 추가 #82
  src/components/score/score.js
  src/components/searchbar/search-Bar.css
  src/components/searchbar/search-Bar.js
Labels: 디자인, 기능추가, 스타일

#86 fix - 치지직 라이브 응답코드 처리 로직 수정
  netlify/functions/api-proxy.js
Labels: 버그

#89 design - 검색 가이드 이미지 로직 수정
  netlify/functions/api-proxy.js
  src/components/live/live.js
  src/components/score/score.css
  src/components/score/score.js
Labels: 버그, 디자인

#91 design : 검색가이드 이미지 수정 완료
  public/images/search-guide--no-result-mobile.png
  public/images/search-guide-mobile.png
  public/images/search-guide-no-result-pc.png
  public/images/search-guide-pc.png
  src/components/score/score.css
  src/components/score/score.js
Labels: 디자인

#94 design - 전적상세 컴포넌트 디자인 및 오류 수정
  src/components/score-detail/score-detail.js
  src/services/api.js
Labels: 디자인, 기능추가

#95 fix : userDetail기능 수정
  src/components/score-detail/score-detail.css
  src/components/score-detail/score-detail.js
Labels: 리팩토링, 디자인, 기능추가

#97 fix - 상세전적 api 로직 예외처리 추가
  netlify/functions/api-proxy.js
Labels: 버그

#101 design : 메인비주얼 텍스트 css 수정 완료
  src/components/main-visual/main-visual.css
Labels: 디자인

#108 docs : 플로우 다이어그램 추가
  README.md
Labels: 문서
